#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, rgba8) uniform readonly image2D InputColor;
layout (set = 1, binding = 0, rgba8) uniform image2D OutputViewport;
layout (set = 1, binding = 1, r32f) uniform image2D OutputViewportZ;

void main() {
    vec4 color = imageLoad(InputColor, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y)).rgba;
    imageStore(OutputViewport, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), color);
}
