#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, rgba8) uniform readonly image2D InColor;
layout (set = 1, binding = 0, rgba8) uniform image2D OutViewport;

void main() {
    vec4 color = imageLoad(InColor, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y)).rgba;
    imageStore(OutViewport, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), color);
}
