#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, rgba8) uniform readonly image2D InputFXAABuffer;
layout (set = 1, binding = 0, rgba8) uniform image2D resultImage;

void main() {
    vec4 color = imageLoad(InputFXAABuffer, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y)).rgba;
    imageStore(resultImage, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), color);
}
