#version 450

layout (local_size_x = 1, local_size_y = 1) in;

struct SSBOIn {
    vec4 Color1;
};
layout(std140, set = 0, binding = 0) readonly buffer ssbosInput
{
    SSBOIn ssboData[];
}ssboInputBuffer;

struct SSBOOut {
    vec4 Color1;
    vec4 Color2;
};
layout(std140, set = 0, binding = 1) buffer ssbosOutput
{
    SSBOOut ssboData[];
}ssboOutputBuffer;


void main() {
    ssboOutputBuffer.ssboData[gl_GlobalInvocationID.x].Color1.rgba = ssboInputBuffer.ssboData[0].Color1.rgba;
}
