#version 450

layout (local_size_x = 16, local_size_y = 16) in;

struct SSBO {
    vec4 Color1;
};
layout(std140, set = 0, binding = 0) readonly buffer ssbosInput
{
    SSBO ssboData[];
}ssboInputBuffer;

layout(std140, set = 0, binding = 1) writeonly buffer ssbosOutput
{
    SSBO ssboData[];
}ssboOutputBuffer;


void main() {
    ssboOutputBuffer.ssboData[0].Color1.rgba = ssboInputBuffer.ssboData[0].Color1.grba;
}
