#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, r8) uniform readonly image3D humongous;
layout (set = 1, binding = 0, rgba8) uniform image2D OutputViewport;

void main() {

    int depth = imageSize(humongous).z;

    vec4 color = imageLoad(humongous, ivec3(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y, depth/2));

    imageStore(OutputViewport, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), vec4(color.rrr, 1.0));
}
