#version 450

layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, rgba8) uniform readonly image2D InputColor;
layout (set = 1, binding = 0, rgba8) uniform image2D OutputViewport;

float random (vec2 st) {
    return fract(sin(dot(st.xy,
    vec2(12.9898,78.233)))*
    43758.5453123);
}

void main() {
    vec4 color = imageLoad(InputColor, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y)).rgba;
    float rnd = random(floor(gl_GlobalInvocationID.xy/512.0*5.0));
    if(rnd > 0.5 && rnd < 0.9) {
        imageStore(OutputViewport, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), 2*color.bgra);
    } else if(rnd <= 0.5 ){
        imageStore(OutputViewport, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), color.rgba);
    } else {
        imageStore(OutputViewport, ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y), vec4(1.0, 0.0, 0.0, 1.0));
    }
}
